# DB
DB_NAME = "bank"

# TABLES

## USERS TABLE
USERS_TABLE_NAME = "users"
USER_ID = "id"
USER_NAME = "name"
USER_BALANCE = "balance"

## CATEGORIES TABLE
CATEGORIES_TABLE_NAME = "categories"
CATEGORY_ID = "id"
CATEGORY_NAME = "name"

## TRANSACTIONS TABLE
TRANSACTIONS_TABLE_NAME = "transactions"
TRANSACTION_ID = "id"
TRANSACTION_AMOUNT = "amount"
TRANSACTION_VENDOR = "vendor"
TRANSACTION_DATE = "date"
TRANSACTION_CATEGORY_ID = "categoryId"
TRANSACTION_USER_ID = "userId"

# JSON DIR
DATA_DIR = "server/db/utils/data.json"

# CONNECTION INFO
CONNECTION_HOST = "localhost"
CONNECTION_USER = "root"
CONNECTION_PASSWORD = ""
CONNECTION_CHARSET = "utf8"
